blank_issues_enabled: false
contact_links:
  - name: Questions about theme and plugins
    url: https://github.com/mdit-plugins/mdit-plugins/discussions/new
    about: Please ask questions in Discussion.
